spring.application.name=gestion-usuarios
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/gestion-usuarios?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mvc.async.request-timeout=180s

# Configuración de sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=update
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD según las entidades (muy usado en desarrollo).
# create: crea las tablas en cada inicio.
# create-drop: igual que create pero borra al apagar.

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect